on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
        run: npm ci
        run: npm run lint
  markdownlint:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
        run: npm ci
        run: npm run markdownlint
  links:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
        run: npm ci
        run: npm run build
        run: npm run test:links